-- Add audit columns (created_by, updated_by) to all application tables that extend BaseEntity
-- Columns are nullable since @CreatedBy/@LastModifiedBy populate them at persist/update time
-- and existing rows can safely have NULL values.

ALTER TABLE users ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE roles ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE roles ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE groups ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE groups ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE permissions ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE permissions ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE billing_records ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE billing_records ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE cost_models ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE cost_models ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE service_usages ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE service_usages ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE change_requests ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE change_requests ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE ci_relationships ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE ci_relationships ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE configuration_items ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE configuration_items ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE services ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE services ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE budgets ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE budgets ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE cost_centers ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE cost_centers ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE expenses ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE invoices ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE invoices ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE payment_records ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE payment_records ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE incidents ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE incidents ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE integration_endpoints ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE integration_endpoints ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE webhook_delivery_logs ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE webhook_delivery_logs ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE assets ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE assets ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE inventory_items ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE inventory_items ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE stock_movements ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE stock_movements ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE warehouses ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE warehouses ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE knowledge_articles ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE knowledge_articles ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE notifications ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE notifications ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE problems ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE problems ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE contracts ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE contracts ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE purchase_orders ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE purchase_orders ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE purchase_requests ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE purchase_requests ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE vendors ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE vendors ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE employees ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE employees ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE skills ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE skills ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE capacity_plans ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE capacity_plans ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE workflow_definitions ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE workflow_definitions ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE workflow_instances ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE workflow_instances ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE approvals ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE approvals ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE assignments ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE assignments ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE comments ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE comments ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE attachments ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE attachments ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE vendor_slas ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE vendor_slas ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE vendor_performances ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE vendor_performances ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE plans ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE plans ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE subscriptions ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);

ALTER TABLE payments ADD COLUMN IF NOT EXISTS created_by VARCHAR(255);
ALTER TABLE payments ADD COLUMN IF NOT EXISTS updated_by VARCHAR(255);
